// <auto-generated />
namespace DominosCMS.Repositories.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Productphoto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Productphoto));
        
        string IMigrationMetadata.Id
        {
            get { return "201301211855505_Product-photo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
