// <auto-generated />
namespace DominosCMS.Repositories.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TechPropViewOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TechPropViewOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201301301718116_TechProp-ViewOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
